# =======================================================
# Spring Boot User & Bookmarks Microservice Configuration
# =======================================================

# Server network listener port
server.port=8082

# Relational Database connection parameters (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/newsdb
spring.datasource.username=newsuser
spring.datasource.password=newsdbpwd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Stateless Session Token Parameters (JWT)
# 256-bit hexadecimal secure signature secret key
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expirations: Access Token = 15 Minutes (900000ms), Refresh Token = 7 Days (604800000ms)
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Swagger Interactive OpenAPI API Specifications Paths
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
